#%RAML 1.0 DataType

type: object
properties:
  id: string
  client_order_id: string
  lines:
    properties:
      id: integer
      sku: integer
      identifier: string
      quantity: integer
      sales_value:
        type: object
        properties:
          amount: number
          currency: string
      batch_details: array
  address:
    type: object
    properties:
      name:
        type: string
        minLength: 5
      line_one:
        type: string
        minLength: 1
      line_two:
        type: string
        minLength: 4
      line_three:
        type: string
      line_four:
        type: string
      town:
        type: string
        minLength: 2
      country_code:
        type: string
      postcode:
        type: string
        minLength: 2
      email_address:
        type: string
        minLength: 5
      phone_number:
        type: string
        minLength: 5
  status: string
  shipping_service: string
  tracking:
    properties:
      dispatched: boolean
      dispatched_from_city: any
      carrier_name: any
      tracking_url: any
      tracking_number: any
      lines:
        properties:
          id: integer
          sku: integer
          client_sku: string
          identifier: string
  note: string
  channel: string
  order_options:
    type: object
    properties:
      has_dispatch_note: boolean
  created_at: string
  